# -*- coding: utf-8 -*-
"""boxplot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g3S3pjdXiZUE0Jls4Ygkeyv4WIVT_tIP
"""

import matplotlib.pyplot as plt
import seaborn as sns

sns.get_dataset_names()

sns.load_dataset("iris")

df = sns.load_dataset("iris")
df.head()

df['sepal_length'].describe()

plt.boxplot(df['sepal_length'])
plt.show()

df['sepal_width'].describe()

plt.boxplot(df['sepal_width'])
plt.show()

sns.boxplot(data = df, x = "species", y = "sepal_length")
plt.show()